"""Seed S3 from the box's on-disk atlases (Phase 3 Step 3 task 8, issue #159).

The one-time move that puts the source of truth in S3. Everything after it —
sessions, publish, the scripts — already assumes the data is there; this is
what puts it there.

**Staging only.** A version used to be a full copy of staging, so the box holds
ten of them for westport alone (6 GB of layers and outlets that are mostly
identical). Carrying that history forward would seed the duplication the
catalog exists to remove, and the history is not lost — it is on the EBS
snapshot, and the first publish after seeding creates the version that matters.

**Derived from config, never from a listing**, for the shared data: only ~20
files in `/root/data` are referenced by any config, and one *unreferenced* file
there is 4.9 GB.

The planners here are pure and take plain paths, so the whole exclusion policy
is testable without S3 or a copy of the box.
"""

from pathlib import Path
import fnmatch
import logging

import atlas_shared
import atlas_store
import atlas_workspace as ws

logger = logging.getLogger(__name__)


# The atlases to migrate, chosen 2026-09-11. Deliberately a list rather than a
# directory scan: /root/swales_dev holds 37 directories, most of them backups,
# test atlases and superseded duplicates (westportdev, king_range_hike, ft1-4,
# *_backup*). Seeding what happens to be on disk would carry all of that into
# the thing that replaces it.
MIGRATE = [
    'abi_demo',
    'angelo',
    'fhe',
    'ft5',
    'gilhamhike',
    'kennedy',
    'king_range',
    'layt1',
    'mineralkinsey',
    'napachar',
    'nfsc_refugia',
    'scvfd',
    'sherwood_ranch',
    'south_fork_eel_2026_10_02',
    'westport',
]


# Paths under staging/ that are never seeded.
#
# Each is regenerated, machine-local, or a credential — never data the atlas
# would lose. `local` is the one that matters most: it is a symlink to the
# shared store, so following it would copy 25 GB into every atlas's prefix.
EXCLUDE_PATTERNS = (
    'local',                        # symlink to the shared store (seeded separately)
    'local/*',
    '.htpasswd',                    # regenerated by every config build
    '*/.htpasswd',
    'atlas_config-BACKUP-*.json',   # the private bucket versions the config itself
    '*.part',                       # interrupted downloads
    '*.lock',
)

# Directory names skipped wherever they appear under staging/.
EXCLUDE_DIRNAMES = ('__pycache__', '.ipynb_checkpoints')

DELTA_ARCHIVE_DIRNAMES = ws.ARCHIVE_DIRNAMES


def is_excluded(rel: str, *, include_delta_archive: bool = True,
                skip_outlets=()) -> bool:
    """Should this staging-relative path be left behind?

    `skip_outlets` names whole outlet directories to drop. It is a per-outlet
    choice rather than a pattern because a QGIS runbook's per-region PDFs sit
    in the same directory as the merged deliverable — there is no filename rule
    that tells the intermediate from the product, and guessing wrong drops
    something a customer is given.
    """
    parts = rel.split('/')

    if any(part in EXCLUDE_DIRNAMES or part.startswith('.') for part in parts[:-1]):
        return True
    for pattern in EXCLUDE_PATTERNS:
        if fnmatch.fnmatch(rel, pattern) or fnmatch.fnmatch(parts[-1], pattern):
            return True

    if not include_delta_archive and ws.is_archive_path(rel):
        return True
    if skip_outlets and len(parts) >= 2 and parts[0] == 'outlets' and parts[1] in skip_outlets:
        return True
    return False


def plan_staging_upload(staging_dir, *, include_delta_archive: bool = True,
                        skip_outlets=()) -> list:
    """`(Path, staging-relative path)` for everything to seed from one atlas.

    Symlinks are **not** followed. `staging/local` points at the 25 GB shared
    store and `app` at a code checkout; both are excluded by name, and not
    following is the backstop that keeps a new one from silently multiplying
    the upload.
    """
    staging_dir = Path(staging_dir)
    if not staging_dir.is_dir():
        return []

    skip_outlets = set(skip_outlets or ())
    plan = []
    for path in sorted(staging_dir.rglob('*')):
        if path.is_symlink() or not path.is_file():
            continue
        rel = path.relative_to(staging_dir).as_posix()
        if is_excluded(rel, include_delta_archive=include_delta_archive,
                       skip_outlets=skip_outlets):
            continue
        plan.append((path, rel))
    return plan


def plan_shared_upload(config: dict, shared_dir) -> tuple:
    """`([(Path, shared-relative path)], [missing])` for one atlas's shared files.

    Missing files are reported rather than raised: the box has several
    pre-existing broken inlet inputs (westport_incidents.geojson,
    documents.zip, a .shp with no siblings) and a seed that refuses to run
    until they are fixed would block the migration on unrelated breakage. They
    are as broken after the move as before it, which is the honest outcome.
    """
    shared_dir = Path(shared_dir)
    plan, missing = [], []
    for rel in atlas_shared.referenced_files(config):
        path = shared_dir / rel
        if path.is_file():
            plan.append((path, rel))
        else:
            missing.append(rel)
    return plan, missing


def summarize(plan) -> dict:
    """`{top-level directory: {'files', 'bytes'}}`, for reading a dry run.

    The point of a dry run here is deciding what not to carry, and that is a
    per-directory judgement — which outlet is 491 MB, whether the delta archive
    is worth its size — so the summary is by directory rather than a total.
    """
    totals = {}
    for path, rel in plan:
        top = rel.split('/')[0] if '/' in rel else '(root)'
        if top in ('outlets', 'layers', 'deltas') and '/' in rel:
            top = '/'.join(rel.split('/')[:2])
        entry = totals.setdefault(top, {'files': 0, 'bytes': 0})
        entry['files'] += 1
        try:
            entry['bytes'] += path.stat().st_size
        except OSError:
            pass
    return totals


def human(size: int) -> str:
    for unit in ('B', 'KB', 'MB', 'GB'):
        if size < 1024 or unit == 'GB':
            return f"{size:.0f}{unit}" if unit == 'B' else f"{size:.1f}{unit}"
        size /= 1024.0


def upload(client, bucket: str, plan, key_for, *, dry_run: bool = False,
           skip_present: bool = True, progress=None) -> dict:
    """Upload a plan, skipping objects S3 already holds with the same bytes.

    `skip_present` makes a re-run cheap and makes an interrupted seed
    resumable: the sha256 metadata is the same one `atlas_workspace` writes and
    checks, so a seeded object and a written-back one are indistinguishable
    afterwards — which is the point. A seed that produced objects a session
    could not recognize would make the first write-back re-upload everything.
    """
    uploaded = skipped = moved = 0
    for path, rel in plan:
        # Before hashing: the digest is only used to skip an object S3 already
        # holds and to stamp the upload, and a dry run does neither. Hashing
        # first made a dry run read every byte it would have uploaded — 794 MB
        # for fhe, 700 for westport — which is most of the cost of the real
        # thing, for a command whose whole point is to be cheap enough to run
        # before deciding.
        if dry_run:
            uploaded += 1
            moved += path.stat().st_size
            continue

        key = key_for(rel)
        digest = ws.sha256_file(path)
        if skip_present and ws._already_uploaded(client, bucket, key, digest):
            skipped += 1
            continue
        with open(path, 'rb') as handle:
            client.put_object(Bucket=bucket, Key=key, Body=handle,
                              ContentType=atlas_store.content_type_for(rel),
                              Metadata={'sha256': digest})
        uploaded += 1
        moved += path.stat().st_size
        if progress:
            progress(rel, uploaded)
    return {'uploaded': uploaded, 'skipped': skipped, 'bytes': moved}
