import os
import json
from pathlib import Path
from typing import List, Dict, Any, Optional
import subprocess
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class GeoPDFGenerator:
    """Generate GeoPDF files from TIFF and GeoJSON layers."""
    
    def __init__(self, output_dir: str = "output"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
        
    def create_geopdf(
        self,
        tiff_path: str,
        geojson_layers: List[Dict[str, Any]],
        output_filename: str,
        title: str = "Atlas Map",
        author: str = "Generated by Atlas",
        subject: str = "Geographic Data",
        creator: str = "Atlas System",
        dpi: int = 300,
        page_size: str = "A4",
        margin_mm: int = 10
    ) -> str:
        """
        Create a GeoPDF from TIFF and GeoJSON layers.
        
        Args:
            tiff_path: Path to the TIFF file (raster layer)
            geojson_layers: List of GeoJSON layer configurations
            output_filename: Name of the output PDF file
            title: PDF title
            author: PDF author
            subject: PDF subject
            creator: PDF creator
            dpi: Output resolution in DPI
            page_size: Page size (A4, A3, Letter, etc.)
            margin_mm: Margin in millimeters
            
        Returns:
            Path to the generated GeoPDF file
        """
        
        output_path = self.output_dir / output_filename
        
        # Step 1: Create a VRT (Virtual Dataset) to combine layers
        vrt_path = self._create_vrt(tiff_path, geojson_layers)
        
        # Step 2: Generate the GeoPDF using gdal2tiles or gdal_translate
        self._generate_geopdf(vrt_path, output_path, dpi, page_size, margin_mm)
        
        # Step 3: Add PDF metadata
        self._add_pdf_metadata(output_path, title, author, subject, creator)
        
        # Clean up temporary files
        if vrt_path.exists():
            vrt_path.unlink()
            
        logger.info(f"GeoPDF created successfully: {output_path}")
        return str(output_path)
    
    def _create_vrt(self, tiff_path: str, geojson_layers: List[Dict[str, Any]]) -> Path:
        """Create a VRT file that combines the TIFF and GeoJSON layers."""
        
        vrt_path = self.output_dir / "temp.vrt"
        
        # Start VRT content
        vrt_content = [
            '<OGRVRTDataSource>',
            f'  <OGRVRTLayer name="raster">',
            f'    <SrcDataSource>{tiff_path}</SrcDataSource>',
            f'    <LayerSRS>EPSG:4326</LayerSRS>',
            f'  </OGRVRTLayer>'
        ]
        
        # Add GeoJSON layers
        for i, layer_config in enumerate(geojson_layers):
            layer_name = layer_config.get('name', f'vector_{i}')
            geojson_path = layer_config['path']
            style_config = layer_config.get('style', {})
            
            vrt_content.extend([
                f'  <OGRVRTLayer name="{layer_name}">',
                f'    <SrcDataSource>{geojson_path}</SrcDataSource>',
                f'    <LayerSRS>EPSG:4326</LayerSRS>',
                f'    <GeometryType>wkbUnknown</GeometryType>'
            ])
            
            # Add styling if provided
            if style_config:
                vrt_content.append(f'    <Style>{self._create_style_xml(style_config)}</Style>')
            
            vrt_content.append(f'  </OGRVRTLayer>')
        
        vrt_content.append('</OGRVRTDataSource>')
        
        # Write VRT file
        with open(vrt_path, 'w') as f:
            f.write('\n'.join(vrt_content))
        
        return vrt_path
    
    def _create_style_xml(self, style_config: Dict[str, Any]) -> str:
        """Create OGR style XML from configuration."""
        
        style_parts = []
        
        if 'color' in style_config:
            color = style_config['color']
            if isinstance(color, list):
                r, g, b = color[:3]
                hex_color = f"#{r:02x}{g:02x}{b:02x}"
            else:
                hex_color = color
            
            style_parts.append(f'<Pen>')
            style_parts.append(f'  <GraphicStroke>')
            style_parts.append(f'    <Graphic>')
            style_parts.append(f'      <Mark>')
            style_parts.append(f'        <WellKnownName>circle</WellKnownName>')
            style_parts.append(f'        <Fill>')
            style_parts.append(f'          <CssParameter name="fill">{hex_color}</CssParameter>')
            style_parts.append(f'        </Fill>')
            style_parts.append(f'      </Mark>')
            style_parts.append(f'    </Graphic>')
            style_parts.append(f'  </GraphicStroke>')
            style_parts.append(f'</Pen>')
        
        if 'width' in style_config:
            style_parts.append(f'<Pen>')
            style_parts.append(f'  <CssParameter name="stroke-width">{style_config["width"]}</CssParameter>')
            style_parts.append(f'</Pen>')
        
        return '\n'.join(style_parts)
    
    def _generate_geopdf(self, vrt_path: Path, output_path: Path, dpi: int, page_size: str, margin_mm: int):
        """Generate the actual GeoPDF file."""
        
        # Method 1: Using gdal2tiles with PDF output
        try:
            cmd = [
                'gdal2tiles',
                '--profile=geodetic',
                f'--zoom=10-15',
                f'--resampling=near',
                '--webviewer=none',
                '--title=Atlas Map',
                '--url=http://example.com/',
                '--pdf',
                str(vrt_path),
                str(output_path.parent / output_path.stem)
            ]
            
            result = subprocess.run(cmd, capture_output=True, text=True, check=True)
            logger.info("GeoPDF generated using gdal2tiles")
            
            # except subprocess.CalledProcessError as e:
        except Exception as e:
            logger.warning(f"gdal2tiles failed: {e}")
            logger.info("Falling back to gdal_translate method")
            
            # Method 2: Using gdal_translate with PDF driver
            self._generate_geopdf_gdal_translate(vrt_path, output_path, dpi, page_size, margin_mm)
    
    def _generate_geopdf_gdal_translate(self, vrt_path: Path, output_path: Path, dpi: int, page_size: str, margin_mm: int):
        """Generate GeoPDF using gdal_translate as fallback."""
        
        # Create a simple PDF using gdal_translate
        cmd = [
            'gdal_translate',
            '-of', 'PDF',
            '-co', f'DPI={dpi}',
            '-co', f'PAGE_SIZE={page_size}',
            '-co', f'MARGIN={margin_mm}',
            str(vrt_path),
            str(output_path)
        ]
        
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        logger.info("GeoPDF generated using gdal_translate")
    
    def _add_pdf_metadata(self, pdf_path: Path, title: str, author: str, subject: str, creator: str):
        """Add metadata to the PDF file."""
        
        # This would require a PDF library like PyPDF2 or reportlab
        # For now, we'll use gdal_translate with metadata options
        temp_path = pdf_path.with_suffix('.temp.pdf')
        
        cmd = [
            'gdal_translate',
            '-of', 'PDF',
            '-co', f'TITLE={title}',
            '-co', f'AUTHOR={author}',
            '-co', f'SUBJECT={subject}',
            '-co', f'CREATOR={creator}',
            str(pdf_path),
            str(temp_path)
        ]
        
        try:
            subprocess.run(cmd, capture_output=True, text=True, check=True)
            temp_path.replace(pdf_path)
            logger.info("PDF metadata added successfully")
        except subprocess.CalledProcessError as e:
            logger.warning(f"Failed to add PDF metadata: {e}")
            if temp_path.exists():
                temp_path.unlink()

def create_atlas_geopdf(
    config: Dict[str, Any],
    atlas_name: str,
    output_dir: str = "output"
) -> str:
    """
    Create a GeoPDF for an atlas based on its configuration.
    
    Args:
        config: Atlas configuration dictionary
        atlas_name: Name of the atlas
        output_dir: Output directory for the PDF
        
    Returns:
        Path to the generated GeoPDF file
    """
    
    generator = GeoPDFGenerator(output_dir)
    
    # Find the TIFF layer (usually the basemap)
    tiff_path = None
    for layer in config['dataswale']['layers']:
        if layer.get('geometry_type') == 'raster':
            layer_path = Path(config['data_root']) / atlas_name / 'staging' / 'layers' / layer['name'] / f"{layer['name']}.tiff"
            if layer_path.exists():
                tiff_path = str(layer_path)
                break
    
    if not tiff_path:
        raise ValueError("No TIFF layer found in atlas configuration")
    
    # Prepare GeoJSON layers
    geojson_layers = []
    for layer in config['dataswale']['layers']:
        if layer.get('geometry_type') in ['polygon', 'linestring', 'point']:
            layer_path = Path(config['data_root']) / atlas_name / 'staging' / 'layers' / layer['name'] / f"{layer['name']}.geojson"
            if layer_path.exists():
                geojson_layers.append({
                    'name': layer['name'],
                    'path': str(layer_path),
                    'style': {
                        'color': layer.get('color', [100, 100, 100]),
                        'width': layer.get('width', 1)
                    }
                })
    
    # Generate the GeoPDF
    output_filename = f"{atlas_name}_atlas.pdf"
    return generator.create_geopdf(
        tiff_path=tiff_path,
        geojson_layers=geojson_layers,
        output_filename=output_filename,
        title=f"{atlas_name} Fire Atlas",
        author="Atlas System",
        subject="Geographic Data",
        creator="Atlas System"
    )

# Example usage
if __name__ == "__main__":
    # Example configuration
    example_config = {
        "name": "wildwood",
        "data_root": "/path/to/data",
        "dataswale": {
            "layers": [
                {
                    "name": "basemap",
                    "geometry_type": "raster"
                },
                {
                    "name": "roads",
                    "geometry_type": "linestring",
                    "color": [255, 0, 0],
                    "width": 2
                },
                {
                    "name": "buildings",
                    "geometry_type": "polygon",
                    "color": [0, 0, 255]
                }
            ]
        }
    }
    
    # Create GeoPDF
    pdf_path = create_atlas_geopdf(example_config, "wildwood")
    print(f"GeoPDF created: {pdf_path}") 
