#!/usr/bin/env python3
"""Generate ISSUES.md — a triage dashboard of GitHub issue *searches*.

The dashboard links to label-filtered searches (priority, area, theme), never to
individual issues, so it stays correct as issues come and go without needing to be
regenerated. Re-run only when the label taxonomy itself changes.

Usage:
    python scripts/gen_issue_dashboard.py            # writes ./ISSUES.md
    python scripts/gen_issue_dashboard.py --check     # fail if ISSUES.md is stale

Owner/repo are read from `git remote get-url origin`, falling back to the
Salmon-Creek-Systems/stewardship_atlas default.
"""
import subprocess
import sys
import re
from pathlib import Path
from urllib.parse import quote_plus

DEFAULT_OWNER_REPO = ("Salmon-Creek-Systems", "stewardship_atlas")

# ── Label taxonomy (keep in sync with the repo labels) ────────────────────────
PRIORITIES = [
    ("P0", "Urgent — silent data loss / production breakage. Fix next."),
    ("P1", "High — real bugs, paying-customer needs, unblocks other work."),
    ("P2", "Medium — solid improvements, non-urgent features."),
    ("P3", "Low — polish, minor annoyances, speculative."),
]

AREAS = [
    ("email-ops",    "Email / photo ingest pipeline + ops"),
    ("map-ui",       "Webmap / webedit / console UI"),
    ("geodata",      "Inlets, eddies, raster/COG/PMTiles, geo data layers"),
    ("biochar",      "Biochar / treatment / soil modeling + ABI demo"),
    ("atlas-create", "Atlas creation / provisioning / starters"),
    ("dagster",      "Orchestration, auto-trigger, refresh / publish"),
    ("config",       "Config naming, structure, consistency, build"),
    ("federation",   "Cross-atlas data federation (STAC)"),
    ("3d-view",      "3D terrain view"),
    ("sql",          "SQL query interface"),
]

THEMES = [
    ("user-facing",       "Affects customer-visible output / experience"),
    ("ux",                "Interaction / usability quality"),
    ("cost-reducing",     "Reduces infra/operational or dev cost"),
    ("extend-processing", "New / expanded computation (eddies, models)"),
    ("extend-data",       "New data sources / layers"),
    ("data-integrity",    "Risk of losing / corrupting data"),
    ("reliability",       "Pipeline robustness / error surfacing"),
    ("tech-debt",         "Refactor / consistency / cleanup"),
    ("security",          "Trust / authorization"),
    ("commercial",        "Tied to paying customer or proposal"),
    ("dev-experience",    "Internal tooling / logging / orchestration"),
]

# Combined searches for common sequencing questions: (title, [labels], note)
COMBOS = [
    ("Do next", ["P0"], "Silent data-loss / production breakage."),
    ("High priority", ["P1"], "Everything ranked high."),
    ("Atlas-creation flow", ["atlas-create"], "The `/create` path has several quiet bugs."),
    ("Email data-integrity cluster", ["email-ops", "data-integrity"], "Submissions being lost."),
    ("Biochar / ABI push", ["biochar", "P1"], "Proposal-facing demo work."),
    ("Cost / cleanup sprint", ["cost-reducing"], "Batchable dedup and infra cleanup."),
    ("Customer-visible quick wins", ["user-facing", "P2"], "Ship-and-notice improvements."),
    ("Tech debt", ["tech-debt"], "Consistency and refactor work."),
    ("Security", ["security"], "Trust / authorization concerns."),
]


def owner_repo():
    try:
        url = subprocess.check_output(
            ["git", "remote", "get-url", "origin"], text=True).strip()
    except Exception:
        return DEFAULT_OWNER_REPO
    m = re.search(r"[:/]([^/]+)/([^/]+?)(?:\.git)?$", url)
    return (m.group(1), m.group(2)) if m else DEFAULT_OWNER_REPO


def search_url(owner, repo, labels, state="open"):
    """Build a GitHub issue-search URL for open issues carrying ALL given labels."""
    terms = ["is:issue", f"is:{state}"] + [f'label:{l}' for l in labels]
    return f"https://github.com/{owner}/{repo}/issues?q={quote_plus(' '.join(terms))}"


def render():
    owner, repo = owner_repo()
    all_open = f"https://github.com/{owner}/{repo}/issues?q={quote_plus('is:issue is:open')}"

    lines = []
    lines.append("# Issue Dashboard")
    lines.append("")
    lines.append(
        "Triage views over the open issues. Each link is a **saved search** by label, "
        "not a list of specific issues — so this page stays current on its own. "
        f"[All open issues]({all_open}).")
    lines.append("")
    lines.append(
        "> Generated by `scripts/gen_issue_dashboard.py`. Don't edit by hand; "
        "re-run the script if the label taxonomy changes.")
    lines.append("")
    lines.append(
        "**How to read it:** priority (`P0`–`P3`) reflects *intrinsic* importance and "
        "is meant to be stable. Area and theme tags carry the sequencing/momentum "
        "signal — combine them (e.g. `P1` + `biochar`) to batch work by initiative.")
    lines.append("")

    lines.append("## Priority")
    lines.append("")
    for name, desc in PRIORITIES:
        lines.append(f"- [`{name}`]({search_url(owner, repo, [name])}) — {desc}")
    lines.append("")

    lines.append("## Areas")
    lines.append("")
    for name, desc in AREAS:
        lines.append(f"- [`{name}`]({search_url(owner, repo, [name])}) — {desc}")
    lines.append("")

    lines.append("## Themes")
    lines.append("")
    for name, desc in THEMES:
        lines.append(f"- [`{name}`]({search_url(owner, repo, [name])}) — {desc}")
    lines.append("")

    lines.append("## Useful combined searches")
    lines.append("")
    for title, labels, note in COMBOS:
        chips = " + ".join(f"`{l}`" for l in labels)
        lines.append(f"- [{title}]({search_url(owner, repo, labels)}) ({chips}) — {note}")
    lines.append("")

    return "\n".join(lines) + "\n"


def main():
    out = Path(__file__).resolve().parent.parent / "ISSUES.md"
    content = render()
    if "--check" in sys.argv:
        current = out.read_text() if out.exists() else ""
        if current != content:
            print(f"{out.name} is stale — run: python scripts/gen_issue_dashboard.py",
                  file=sys.stderr)
            sys.exit(1)
        print(f"{out.name} is up to date.")
        return
    out.write_text(content)
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
